language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.3
    - android-27
    - extra-android-m2repository
  licenses:
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    - 'intel-android-extra-license-.+'

jdk:
  - oraclejdk8

branches:
  only:
    - master
    # RC Tag Branches
    - /^\d+\.\d+\.\d+-rc\d+$/
    # Release Tag Branches
    - /^\d+\.\d+\.\d+$/
    # Preview Release Tag Branches
    - /^\d+\.\d+\.\d+-preview\d+$/
    # Beta Release Tag Branches
    - /^\d+\.\d+\.\d+-beta\d+$/

stages:
  - name: release candidate
    if: tag =~ ^\d+\.\d+\.\d+-rc\d+$
  - name: release
    if: tag =~ ^\d+\.\d+\.\d+$ OR tag =~ ^\d+\.\d+\.\d+-preview\d+$ OR tag =~ ^\d+\.\d+\.\d+-beta\d+$

notifications:
  slack:
    secure: RYo4Cc27ncThXlhVOTlFCPmzjB6p+Zcdnh5sKdEb5Nnv4IwAnw3QwjX87oSJwyerwI/C1EKLaeOKFMAycEHCmBXj5C5HTF+PnZrkYJwbMsPOsCcZLn0r/e0yxKmdg+MK7WTNXgt+WOfxvSbjmQ2WfE4OJAjHe+rOAC5OqHn4ukg/RmDN36lfZulhJ1hXjXIvBWOvpqy37AseSjzvS0VWGje9fJOPspTxr286N2kwfdNpoqi5X1f2RWa5BOLzs4sfdZZ7ijVIdGad/3Qf079baJ0Iz4qvruiAY2rUf+Vlj/x4u/BMXtv960D/jNOEWUQw4oZoEtCh6dBWi8n0JKB36yFc0P4Utvl9JTiaqyMUFh2OXAIbzLAFPmJF/3MdnKrGjV8+M8WzH+akjQCsXN2xxgxnIBwq25F4fFaacaxve2Pr7S9mu8k9cd2P2EfM88/JIv6W+3yqnM9GgkweX3h5OUaZI1JpV7/PR8KhjHJp7XgOu7V7gsRHWEhUVTK7pzEwP93w5sh/UZpaTZBViJlHSKma1Ap7c1/+p4vn3WQD2QTHU85Rr0hQFlC08QmlQQt8R1k9U+mMLFkgJpFxL4ba1fVO7ojVMKsxE+sccaWTTLG33XnfEIwI5YDdFE+uOtk3kkhtbi2s6nht4IUHuBJLj5mgacV+9kVu3o6y/izbZQQ=
  webhooks:
    urls:
      secure: AS7QcrL2IMQKyi7Edp8dmG6c+txtAyAXOwn4sz0wiLSC5WMYDE8k61ybQfM4RoNLkaZcExq3LlXEYjBmOd4npRisgpd9+li40j0aAQUcx8XhaiexMZB3icL/ZVeViJMtDCgaZRhEkWIokPVtNXNgleHiEhaJ/iOUE3LjuONlGma/jX+zvYYslzEorVEFN6zxSURA7ViA8Ynh+umm/Xy9wZffggbzBjAZqQqoittc8crZF+CY6+Kw5r8lVcKR+QslaXkU1N6iNV1buW30X3F+3Ieem79SViBCB9SLzltanWwdBY4e0eQC2JQ4Q9Qj7AEczMg6nb8EI0UYAsO4y7cD/JlIrte4VQdgkkABu3Uq2P41pTHOA7SrIKeG+0V0xEUeto0/Edm+pE2ucejr9wD6NaeryHcvuC3KZYH3Mjj6OyLXhhyo54W/BK7BZr2O02jCVG6dQ74E12EeBx8Ji745nCcCtIaWvv3ZPOR+ubMHR5oALcXV97ePEw1e03wyjNCO9gNc3dZekkmhaDSjZCF06P6g8YX8rybvnVFq/qzCwa5QwGCTsw7GV5F2BPGrbSDe+kqaweogrRVrxGbebJHQcK1QqZ7LZTaYHyOR3ao2/lyjmVUIn74AFn0N0TceGDMbAiSa75TIGqSLaa7TeP9zljMs3f4WfUdjUrdrHNZ2qXw=
    on_success: always

before_install:
  # Travis CI has not been setup to install Android 27. This workaround ensures the SDK is properly
  # installed and the license agreement is accepted. See Stackoverflow post below:
  # https://stackoverflow.com/questions/47719282/i-cant-build-android-27-tool-27-0-2-with-travis-ci/47726910#47726910
  - yes | sdkmanager "platforms;android-27"

  # Install all Android SDK tools
  - yes | sdkmanager "tools"

  # Ensures commands stop running after the first failed command
  - set -eo pipefail

  # Setup secrets
  - |
    if [ $TRAVIS_SECURE_ENV_VARS = true ]; then
      # Untar secrets
      openssl aes-256-cbc -K $encrypted_7f5144414b5d_key -iv $encrypted_7f5144414b5d_iv -in secrets.tar.enc -out secrets.tar -d
      tar -xvf secrets.tar

      # Internal debug google services
      mkdir -p app/src/internal/debug || true
      cp secrets/internal-debug-google-services.json app/src/internal/debug/google-services.json

      # Internal release google services
      mkdir -p app/src/internal/release || true
      cp secrets/internal-release-google-services.json app/src/internal/release/google-services.json

      # Twilio release google services
      mkdir -p app/src/twilio/release || true
      cp secrets/twilio-release-google-services.json app/src/twilio/release/google-services.json

      # Video Android Twilio Credentials
      cp secrets/twilio-video.json library/twilio-video.json

      # Video App Development Variant Credentials
      cp secrets/twilio-video-app.json app/twilio-video-app.json

      # Authenticate with gcloud
      gcloud auth activate-service-account travis@video-app-79418.iam.gserviceaccount.com --key-file=secrets/video-app-46437ca14fdd.json

      # Android Keystore
      echo "androidKeystore=$TRAVIS_BUILD_DIR/$ANDROID_KEYSTORE" >> $HOME/.gradle/gradle.properties
      echo "androidKeystorePassword=$ANDROID_KEYSTORE_PASSWORD" >> $HOME/.gradle/gradle.properties
      echo "androidReleaseKeyAlias=$ANDROID_RELEASE_KEY_ALIAS" >> $HOME/.gradle/gradle.properties
      echo "androidReleaseKeyPassword=$ANDROID_RELEASE_KEY_PASSWORD" >> $HOME/.gradle/gradle.properties
    fi

  # Reset initial pipefail settings
  - set +eo pipefail

before_script:
   # Gradle
   - echo "org.gradle.jvmargs=-Xmx4096M" >> $HOME/.gradle/gradle.properties

   # Git
   - git config --global user.email "twilio-sdk-build@twilio.com"
   - git config --global user.name "twilio-sdk-build"

   # Cmake
   - wget https://github.com/Commit451/android-cmake-installer/releases/download/1.1.0/install-cmake.sh
   - chmod +x install-cmake.sh
   - ./install-cmake.sh > /dev/null

   # Google Cloud SDK
   - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
   - source /home/travis/google-cloud-sdk/path.bash.inc
   - gcloud version

   # Android NDK Setup
   - pushd ~
   - wget -q https://dl.google.com/android/repository/android-ndk-r12b-linux-x86_64.zip
   - unzip -qo android-ndk-r12b-linux-x86_64.zip
   - export ANDROID_NDK_HOME="$HOME/android-ndk-r12b"
   - popd

cache:
  directories:
    - $HOME/.gradle
    - $HOME/google-cloud-sdk

jobs:
  include:
    - stage: release candidate
      script: ./gradlew bintrayLibraryReleaseCandidateUpload incrementRc
    - stage: release candidate
      script: ./gradlew -q -PreleaseCandidate=true app:uploadInternalReleaseToHockeyApp
    - stage: release
      script: ./gradlew bintrayLibraryReleaseUpload publishLibraryJavadocs incrementVersion
