version: 2.0

aliases:
  # Workspace
  - &workspace
    ~/twilio-video-android

  # Cache
  - &android-ndk-cache-key
    key: android-ndk-r16b-{{ checksum "scripts/install-android-ndk.sh" }}
  - &restore-cache-android-ndk
    <<: *android-ndk-cache-key
    name: Restore Android NDK
  - &save-cache-android-ndk
    <<: *android-ndk-cache-key
    name: Save Android NDK Cache
    paths:
      - /opt/android-ndk

  - &gradle-cache-key
    key: jars-{{ checksum "build.gradle" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}
  - &restore-cache-gradle
    <<: *gradle-cache-key
    name: Restore Gradle Cache
  - &save-cache-gradle
    <<: *gradle-cache-key
    name: Save Gradle Cache
    paths:
      - ~/.gradle/caches
      - ~/.gradle/wrapper

  # Dependencies
  - &create-android-ndk-directory
    name: Create Android NDK Directory
    command: |
      if [[ ! -e /opt/android-ndk ]]; then
        sudo mkdir /opt/android-ndk
      fi
      sudo chown ${USER:=$(/usr/bin/id -run)}:$USER /opt/android-ndk
  - &install-android-ndk
    name: Install Android NDK
    command: scripts/install-android-ndk.sh

  - &decrypt-secrets
    name: Decrypt secrets
    command: |
      # Untar secrets
      openssl aes-256-cbc -K $encrypted_7f5144414b5d_key -iv $encrypted_7f5144414b5d_iv -in secrets.tar.enc -out secrets.tar -d
      tar -xf secrets.tar
  - &install-secrets
    name: Install secrets
    command: |
      # Internal debug google services
      mkdir -p app/src/internal/debug || true
      cp secrets/internal-debug-google-services.json app/src/internal/debug/google-services.json
      # Internal release google services
      mkdir -p app/src/internal/release || true
      cp secrets/internal-release-google-services.json app/src/internal/release/google-services.json
      # Twilio release google services
      mkdir -p app/src/twilio/release || true
      cp secrets/twilio-release-google-services.json app/src/twilio/release/google-services.json
      # Video Android Twilio Credentials
      echo $TWILIO_VIDEO_ANDROID_FTL_CREDENTIALS | base64 -di > library/twilio-video.json
      # Video App Development Variant Credentials
      echo $TWILIO_VIDEO_ANDROID_FTL_CREDENTIALS | base64 -di > app/twilio-video-app.json
      # Android Keystore
      mkdir -p ~/.gradle
      echo "androidKeystore=$PWD/secrets/android.keystore" >> ~/.gradle/gradle.properties
      echo "androidKeystorePassword=$ANDROID_KEYSTORE_PASSWORD" >> ~/.gradle/gradle.properties
      echo "androidReleaseKeyAlias=$ANDROID_RELEASE_KEY_ALIAS" >> ~/.gradle/gradle.properties
      echo "androidReleaseKeyPassword=$ANDROID_RELEASE_KEY_PASSWORD" >> ~/.gradle/gradle.properties
  - &install-cmake
    name: Install Cmake
    command:
      sdkmanager "cmake;3.6.4111459"
  - &gcloud-auth
    name: Google Cloud Auth
    command: >
              gcloud auth activate-service-account travis@video-app-79418.iam.gserviceaccount.com
              --key-file=secrets/video-app-46437ca14fdd.json

  # Configure git user
  - &configure-git-user
    name: Configure git user
    command: |
      git config --global user.email "twilio-sdk-build@twilio.com"
      git config --global user.name "twilio-sdk-build"

  # Filters
  - &filter-snapshot
    branches:
      only:
        - "master"

  # Containers
  - &build-defaults
    working_directory: *workspace
    docker:
      - image: circleci/android:api-28-node@sha256:a8d15723766a8f32f1a4ead42c5441bb0ded2e832329291cb4bbd9f1d1557721
    environment:
      - _JAVA_OPTIONS: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"

  - &test-defaults
    working_directory: *workspace
    docker:
      - image: google/cloud-sdk:latest
    environment:
    resource_class: medium+

  - &snapshot-defaults
    filters: *filter-snapshot
    requires:
        - check-format
        - check-library-size
        - unit-test
        - integration-virtual-device-test
        - integration-physical-device-test
        - integration-camera-test

  - &rc-defaults
    filters:
      tags:
        only:
          - /^\d+\.\d+\.\d+-rc\d+$/
          - /^\d+\.\d+\.\d+-preview\d+-rc\d+$/
          - /^\d+\.\d+\.\d+-beta\d+-rc\d+$/
      branches:
        ignore: /.*/

  - &release-defaults
    filters:
      tags:
        only:
          - /^\d+\.\d+\.\d+$/
          - /^\d+\.\d+\.\d+-preview\d+$/
          - /^\d+\.\d+\.\d+-beta\d+$/
      branches:
        ignore: /.*/

jobs:
  setup-workspace:
    <<: *build-defaults
    resource_class: medium+
    steps:
      # Setup code and workspace for downstream jobs
      - checkout
      - restore-cache: *restore-cache-gradle
      - run: *create-android-ndk-directory
      - restore-cache: *restore-cache-android-ndk
      - run: *install-android-ndk
      - run: *decrypt-secrets
      - persist_to_workspace:
          root: .
          paths:
            - secrets

      # Save cache
      - save-cache: *save-cache-android-ndk
      - save-cache: *save-cache-gradle

  check-format:
    <<: *build-defaults
    resource_class: medium+
    steps:
      # Setup
      - checkout
      - restore-cache: *restore-cache-gradle
      - run: *create-android-ndk-directory
      - restore-cache: *restore-cache-android-ndk
      - run: *install-android-ndk

      # Run spotless check
      - run:
          name: Spotless Check
          command: ./gradlew -q spotlessCheck

      # Save cache
      - save-cache: *save-cache-gradle
      - save-cache: *save-cache-android-ndk

  build-app:
    <<: *build-defaults
    resource_class: xlarge
    steps:
      # Setup
      - checkout
      - attach_workspace:
          at: *workspace
      - restore-cache: *restore-cache-gradle
      - run: *create-android-ndk-directory
      - restore-cache: *restore-cache-android-ndk
      - run: *install-android-ndk
      - run: *install-secrets
      - run: *install-cmake

      # Build app
      - run:
          name: Build App
          command: ./gradlew -q app:assemble

      # Save the builds to workspace
      - persist_to_workspace:
          root: .
          paths:
            - app/build

      # Save cache
      - save-cache: *save-cache-android-ndk
      - save-cache: *save-cache-gradle

  build-library:
    <<: *build-defaults
    resource_class: xlarge
    steps:
      # Setup
      - checkout
      - attach_workspace:
          at: *workspace
      - restore-cache: *restore-cache-gradle
      - run: *create-android-ndk-directory
      - restore-cache: *restore-cache-android-ndk
      - run: *install-android-ndk
      - run: *install-secrets
      - run: *install-cmake

      # Build library and tests
      - run:
          name: Build Library and Tests
          command: ./gradlew -q library:assemble library:assembleAndroidTest

      # Save the builds to workspace
      - persist_to_workspace:
          root: .
          paths:
            - library/build

      # Save cache
      - save-cache: *save-cache-android-ndk
      - save-cache: *save-cache-gradle

  check-library-size:
    <<: *build-defaults
    resource_class: large
    steps:
      # Setup
      - checkout
      - attach_workspace:
          at: *workspace
      - restore-cache: *restore-cache-gradle
      - run: *create-android-ndk-directory
      - restore-cache: *restore-cache-android-ndk
      - run: *install-android-ndk
      - run: *install-cmake

      # Check library size
      - run:
          name: Check Library Size
          command: ./gradlew -q librarySizeReport

      # Save cache
      - save-cache: *save-cache-android-ndk
      - save-cache: *save-cache-gradle

  unit-test:
    <<: *build-defaults
    resource_class: medium+
    steps:
      # Setup
      - checkout
      - attach_workspace:
          at: *workspace
      - restore-cache: *restore-cache-gradle
      - run: *create-android-ndk-directory
      - restore-cache: *restore-cache-android-ndk
      - run: *install-android-ndk

      # Run unit tests
      - run:
          name: Unit Tests
          command: ./gradlew library:testDebugUnitTest

      # Save cache
      - save-cache: *save-cache-gradle

  integration-virtual-device-test:
    <<: *test-defaults
    steps:
      # Setup
      - checkout
      - attach_workspace:
          at: *workspace
      - run: *gcloud-auth

      # Execute tests
      - run:
          name: Integration Virtual Devices Tests
          command: >
                    gcloud firebase test android run --no-record-video --project video-app-79418
                    video-app-args.yaml:library-virtual-device-tests
  integration-physical-device-test:
    <<: *test-defaults
    steps:
      # Setup
      - checkout
      - attach_workspace:
          at: *workspace
      - run: *gcloud-auth

      # Execute tests
      - run:
          name: Integration Physical Devices Tests
          command: >
                    gcloud firebase test android run --no-record-video --project video-app-79418
                    video-app-args.yaml:library-physical-device-tests

  integration-camera-test:
    <<: *test-defaults
    steps:
      # Setup
      - checkout
      - attach_workspace:
          at: *workspace
      - run: *gcloud-auth

      # Execute tests
      - run:
          name: Instrumentation Camera Tests
          command: >
                    gcloud firebase test android run --no-record-video --project video-app-79418
                    --async video-app-args.yaml:library-camera-tests

  publish-library-snapshot:
    <<: *build-defaults
    resource_class: large
    steps:
      # Setup
      - checkout
      - attach_workspace:
          at: *workspace
      - restore-cache: *restore-cache-gradle
      - run: *create-android-ndk-directory
      - restore-cache: *restore-cache-android-ndk
      - run: *install-android-ndk
      - run: *install-secrets
      - run: *install-cmake

      # Publish library snapshot
      - run:
          name: Publish Library Snapshot
          command: ./gradlew -q -Psnapshot=true bintrayLibrarySnapshotUpload

      # Save cache
      - save-cache: *save-cache-android-ndk
      - save-cache: *save-cache-gradle

  publish-app-snapshot:
    <<: *build-defaults
    resource_class: large
    steps:
      # Setup
      - checkout
      - attach_workspace:
          at: *workspace
      - restore-cache: *restore-cache-gradle
      - run: *create-android-ndk-directory
      - restore-cache: *restore-cache-android-ndk
      - run: *install-android-ndk
      - run: *install-secrets
      - run: *install-cmake

      # Publish app snapshot
      - run:
          name: Publish App Snapshot
          command: >
                    ./gradlew -q
                    -Psnapshot=true
                    app:uploadInternalReleaseToHockeyApp
      # Save cache
      - save-cache: *save-cache-android-ndk
      - save-cache: *save-cache-gradle

  publish-library-rc:
    <<: *build-defaults
    resource_class: xlarge
    steps:
      # Setup
      - checkout
      - attach_workspace:
          at: *workspace
      - restore-cache: *restore-cache-gradle
      - run: *create-android-ndk-directory
      - restore-cache: *restore-cache-android-ndk
      - run: *install-android-ndk
      - run: *install-secrets
      - run: *install-cmake
      - run: *configure-git-user

      # Publish library rc
      - run:
          name: Publish Library RC
          command: ./gradlew bintrayLibraryReleaseCandidateUpload librarySizeReport incrementRc

      # Send webhook if successful
      - run:
          command: ./scripts/send-circleci-webhook.sh
          when: on_success

      # Save cache
      - save-cache: *save-cache-android-ndk
      - save-cache: *save-cache-gradle

  publish-app-rc:
    <<: *build-defaults
    resource_class: xlarge
    steps:
      # Setup
      - checkout
      - attach_workspace:
          at: *workspace
      - restore-cache: *restore-cache-gradle
      - run: *create-android-ndk-directory
      - restore-cache: *restore-cache-android-ndk
      - run: *install-android-ndk
      - run: *install-secrets
      - run: *install-cmake

      # Publish app RC
      - run:
          name: Publish App RC
          command: >
                    ./gradlew -q
                    -PreleaseCandidate=true
                    app:uploadInternalReleaseToHockeyApp

      # Save cache
      - save-cache: *save-cache-android-ndk
      - save-cache: *save-cache-gradle

  publish-library:
    <<: *build-defaults
    resource_class: xlarge
    steps:
      # Setup
      - checkout
      - attach_workspace:
          at: *workspace
      - restore-cache: *restore-cache-gradle
      - run: *create-android-ndk-directory
      - restore-cache: *restore-cache-android-ndk
      - run: *install-android-ndk
      - run: *install-secrets
      - run: *install-cmake
      - run: *configure-git-user

      # Publish library
      - run:
          name: Publish Library
          command: >
                    ./gradlew bintrayLibraryReleaseUpload librarySizeReport publishLibraryJavadocs
                    incrementVersion

      # Send webhook if successful
      - run:
          command: ./scripts/send-circleci-webhook.sh
          when: on_success

      # Save cache
      - save-cache: *save-cache-android-ndk
      - save-cache: *save-cache-gradle

workflows:
  version: 2

  build-test-publish:
    jobs:
      # Setup
      - setup-workspace

      # Build
      - build-app:
          requires:
              - setup-workspace
      - build-library:
          requires:
              - setup-workspace
      - check-format:
          requires:
              - setup-workspace
      - check-library-size:
          requires:
              - setup-workspace

      # Test
      - unit-test:
          requires:
              - build-library
      - integration-virtual-device-test:
          requires:
              - build-library
      - integration-physical-device-test:
          requires:
              - build-library
      - integration-camera-test:
          requires:
              - build-library

      # Publish
      - publish-library-snapshot:
          <<: *snapshot-defaults

      - publish-app-snapshot:
          <<: *snapshot-defaults

  release-candidate:
    jobs:
      # Setup
      - setup-workspace:
          <<: *rc-defaults

      # Publish
      - publish-library-rc:
          <<: *rc-defaults
          context: sdks
          requires:
              - setup-workspace

      - publish-app-rc:
          <<: *rc-defaults
          requires:
              - setup-workspace
  release:
    jobs:
      # Setup
      - setup-workspace:
          <<: *release-defaults

      # Publish
      # TODO: Add publishing app to Play Store VIDEOAPP-15
      - publish-library:
          <<: *release-defaults
          context: sdks
          requires:
              - setup-workspace
